#!/usr/bin/env python

# Driver for building, running and fuzzing the instrumented BOOM simulation.
# Usage:
#    build <CONFIG> -> build a chip configuration
#    run   <BINARY> -> run a binary on the simulation
#    fuzz  <CONFIG> -> fuzz the simulation

import argparse
import sys
import os
import subprocess
import shutil

import multiprocessing

BOOM_CONFIGS = ['FuzzConfig',
                'DebugConfig',
                'MDSConfig',
                'StandardPredConfig',
                'SmallFuzzConfig'
                ]

def build_simulation_name(config: str, debug: bool, old=False):
    if old:
        return f"./simulator-chipyard-{config}-debug" if debug else f"./simulator-chipyard-{config}"
    return f"./run-{config}-debug" if debug else f"./run-{config}"


def build_loadmem_flags(loadmem_file: str, loadmem_addr: str):
    return f"+permissive +loadmem={loadmem_file} +loadmem_addr={loadmem_addr} +permissive-off"


def elf2hex(elf: str, out: str):
    command = f"/chipyard/scripts/smartelf2hex.sh {elf} > {out}"
    subprocess.run(command, shell=True)

def fail(msg):
    print('ERROR: ' + msg)
    sys.exit(-1)

def warn(msg):
    print('WARNING: ' + msg)


class Cmd:
    """
    Helper to build and run PhantomTrails commands.
    """

    def __init__(self):
        # Env flags
        self.env = ''
        # AFL command (if we're fuzzing)
        self.fuzz_cmd = ''
        # Path of the verilated simulation binary
        self.sim = ''
        # Path of the RISCV program to run on the simulation
        self.bin = ''
        # Path of the simulated ROM contents
        self.rom = ''
        # Decides the maximum number of cycles for this binary
        self.cycles = 20
        # Path of the initialization code (loaded before self.bin in memory)
        self.init = ''
        # Additional args
        self.additional = ''

    @classmethod
    def from_args(cls, args, program):
        cmd = Cmd()

        if args.mds:
            cmd.env = f"MDS=1 MDS_INIT={args.mds_init} MDS_TAINT_CYCLE={args.mds_taint_cycle} "
            config = "MDSConfig"
        else:
            config = args.config

        cmd.sim = build_simulation_name(config, debug=False)
        cmd.bin = program
        cmd.rom = args.rom
        cmd.cycles = args.cycles
        cmd.init = args.init

        if args.opt != 'all':
            if args.opt == 'none':
                cmd.remove_dataflow_opt()
                cmd.remove_controlflow_opt()
                cmd.remove_basic_opt()
            elif args.opt == 'basic':
                cmd.remove_dataflow_opt()
                cmd.remove_controlflow_opt()
            elif args.opt == 'dataflow':
                cmd.remove_controlflow_opt()
            elif args.opt == 'controlflow':
                cmd.remove_dataflow_opt()

        return cmd

    def __str__(self):
        return f"{self.env} {self.fuzz_cmd} {self.sim} {self.bin} {self.rom} {self.cycles} {self.init} {self.additional}"

    def run(self):
        print(f"Executing: {str(self)}")
        subprocess.run(str(self), shell=True)

    def add_env_var(self, name, val=None):
        if val is not None:
            self.env += f" {name}={val}"
        else:
            self.env += f" {name}=1"

    def remove_dataflow_opt(self):
        self.init = '/boom-wrapper/init/init-no-dataflow.bin'

    def remove_controlflow_opt(self):
        self.add_env_var("PHANTOM_TRAILS_NO_ILLEGAL_JUMPS")
        self.add_env_var("PHANTOM_TRAILS_NO_SNIPPET")

    def remove_basic_opt(self):
        self.add_env_var("PHANTOM_TRAILS_NO_ARG_REUSE")


#
# export CFLAGS = "$CFLAGS -DFuzzConfig"
# export CXXFLAGS = "$CXXFLAGS -DFuzzConfig"
# make -j8 CONFIG=FuzzConfig SBT_PROJECT=fuzz MODEL_PACKAGE=chipyard MODEL=TestHarness debug
#
def build_sim(args):
    jobs = multiprocessing.cpu_count() if args.jobs is None else args.jobs

    # Add a DEFINE to the compilation flags to tell our custom test harness
    # which config is being built
    os.environ['CFLAGS'] = os.environ['CFLAGS'] + " -D" + args.config
    os.environ['CXXFLAGS'] = os.environ['CXXFLAGS'] + " -D" + args.config

    # Choose sanitizer (DFSAN or MSAN).
    os.environ['CFLAGS'] = os.environ['CFLAGS'] + " -D" + args.sanitizer
    os.environ['CXXFLAGS'] = os.environ['CXXFLAGS'] + " -D" + args.sanitizer

    if args.debug:
        os.environ['CFLAGS'] = os.environ['CFLAGS'] + " -DDEBUG"
        os.environ['CXXFLAGS'] = os.environ['CXXFLAGS'] + " -DDEBUG"

    # Run make
    command = ['make', '-j', str(jobs), f'CONFIG={args.config}',
               'SBT_PROJECT=fuzz', 'MODEL_PACKAGE=chipyard',
               'MODEL=TestHarness']  # f"VERILATOR_THREADS={verilator_threads}"
    if args.debug_chip:
        command.append("debug")

    print(f"Executing: {' '.join(command)}")
    subprocess.check_call(command)

    # if args.trace:
    #     # Rename the simulation binary to its standard name
    #     shutil.move(build_simulation_name(config, True), build_simulation_name(config, False))

#
# run-FuzzConfig binary bootrom.img 20 init.bin 2>&1 | tee out.log
#
def run_sim(args):
    cmd = Cmd.from_args(args, program=args.binary)

    if args.code_regions is not None:
        cmd.add_env_var("CODE_REGIONS", f"{args.code_regions}")
    if args.verbose or args.report:
        cmd.add_env_var("VERBOSE_SIM")
        cmd.add_env_var("VERBOSE_ISA")
        if args.report:
            cmd.add_env_var("PRINT_CYCLES")
            cmd.add_env_var("PRINT_COVERAGE")
            cmd.add_env_var("PRINT_ROB")
            cmd.add_env_var("CRASH_REPORT")
            cmd.add_env_var("MEMDUMP")

    if args.logfile:
        cmd.additional += f" > {args.logfile} 2>&1"

    cmd.run()

#
# mkdir in
# mkdir out
# touch in/seed
# sim-fuzzer -c 1-`nprocs` -i in/ -o out/ -s run-FuzzConfig @@ bootrom.img 20 init.bin
#
def run_fuzzer(args):
    # Create dirs needed by the fuzzer.
    os.makedirs(args.indir, exist_ok=True)
    os.makedirs(args.outdir, exist_ok=True)
    # Create empty seed.
    open(f"{args.indir}/seed", "w").close()
    # Save environment for future debugging.
    with open(f"{args.outdir}/environment", "w") as f:
        for e in os.environ:
            f.write(f"{e}={os.environ[e]}\n")

    # In AFL, "@@" means the fuzzer-generated program.
    cmd = Cmd.from_args(args, program="@@")
    # Construct fuzzing command.
    cmd.fuzz_cmd = f"{args.aflpath} -i {args.indir} -o {args.outdir}"
    if args.simple_ui:
        # Disable tui.
        cmd.fuzz_cmd += " -s"

    # Save command for future debugging.
    with open(f"{args.outdir}/pt_launch_command", "w") as f:
        f.write(str(cmd))

    cmd.run()

#
# ./simulator-chipyard-MediumBoomConfig -V +permissive +loadmem=test.hex +loadmem_addr=80000000 +permissive-off test.riscv 2>&1 | spike-dasm | tee out.log
#
def run_sim_old(args):
    # Transform the input elf into an hex file, to load it quicker.
    hex_to_load = None
    if not args.skip_loadmem:
        print("[+] running elf2hex")
        elf2hex(args.binary, "binary_to_load.hex")
        hex_to_load = "binary_to_load.hex"
        print("[+] Done!")

    print("[+] Running simulation")

    sim_binary = build_simulation_name(args.config, debug=False, old=True)
    verbose_flag = "-c -V" if args.verbose else ""

    if hex_to_load is not None:
        loadmem_flags = build_loadmem_flags(hex_to_load, args.loadmem_addr)
    else:
        loadmem_flags = ""

    dasm_helper = " 2>&1 | sed -e '/^ /s/(0x/DASM(/g' | spike-dasm" if args.dasm else ""
    logger = f" | tee {args.logfile}" if args.logfile != "" else ""

    command = f"{sim_binary} {verbose_flag} --max-cycles={args.cycles} {loadmem_flags} {args.binary}  {dasm_helper} {logger}"
    print(f"Executing: {command}")
    subprocess.run(command, shell=True)

    print(f"[+] Sim ended. Make sure you compiled the program with the right linker.")

def validate(args):
    if '--mds' in sys.argv and '--config' in sys.argv:
        fail("--mds can only be used with MDSConfig, remove the --config flag")
    if '--mds-init' in sys.argv and not '--mds' in sys.argv:
        fail("--mds-init can only be used with --mds")
    if '--mds-taint-cycle' in sys.argv and not '--mds' in sys.argv:
        fail("--mds-taint-cycle can only be used with --mds")

    if '--mds-init' in sys.argv and not '--mds-taint-cycle' in sys.argv:
        warn(
            "If you are using a custom mds-init you should also provide --mds-taint-cycle")

    return


if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description='A pre-silicon fuzzer for transient vulnerabilities.')
    subparsers = parser.add_subparsers(dest='cmd_name')

    # Flags shared by every command.
    parent = argparse.ArgumentParser(add_help=False)
    parent.add_argument(
        '--config', choices=BOOM_CONFIGS, default='FuzzConfig', help='Which BOOM config')

    # Build command.
    build_flags = subparsers.add_parser('build', parents=[parent],
                                        help='Build an instrumented BOOM simulation.')
    build_flags.add_argument(
        '--debug', action='store_true', help='Build with simulation logs')
    build_flags.add_argument(
        '--debug_chip', action='store_true', help='Build with chisel logs')
    build_flags.add_argument(
        '--sanitizer', choices=['DFSAN', 'MSAN'], default='MSAN', help='Choose sanitizer (DFSAN or MSAN)')
    build_flags.add_argument(
        '-j', '--jobs', type=int, default=8, help='Build-time jobs')
    build_flags.set_defaults(func=build_sim)

    # Flags shared by 'run' and 'fuzz'.
    runtime_common = argparse.ArgumentParser(add_help=False)
    runtime_common.add_argument(
        '--cycles', type=int, default=20, help='Multiplication factor for the total amount of cycles (gets multiplied to the number of instructions)')
    runtime_common.add_argument(
        '--rom', default='/boom-wrapper/boot/bootrom.rv64.img', help='Path of the ROM image')
    runtime_common.add_argument(
        '--init', default='/boom-wrapper/init/init.bin', help='Path of the init code, can be empty')
    runtime_common.add_argument(
        '--mds', action='store_true', help='Run in MDS-detection mode (taint buffers after initialization)')
    runtime_common.add_argument(
        '--mds-init', default='/boom-wrapper/init/init-mds.bin', help='Path of the MDS init code (use with --mds)')
    runtime_common.add_argument(
        '--mds-taint-cycle', type=int, default=1733, help='Last cycle of the MDS initialization (use with --mds and --mds-init)')
    runtime_common.add_argument(
        '--opt', choices=['none', 'basic', 'dataflow', 'controlflow', 'all'], default='all',
        help='Control which fuzzing optimizations are enabled. All are on by default. Note that \'controlflow\' and \'dataflow\' imply \'basic\'.')

    # Run command.
    run_flags = subparsers.add_parser('run', parents=[parent, runtime_common],
                                      help='Run a RISCV program on the simulator.')
    run_flags.add_argument(
        'binary', help="Program to run, in raw binary format (_not_ ELF)")
    run_flags.add_argument(
        '--verbose', action='store_true', help="Enable simulation logs")
    run_flags.add_argument(
        '--code_regions', help="File specifying which regions contain code (default is the whole binary).")
    run_flags.add_argument(
        '--logfile', help="Where to log the simulation's output")
    run_flags.add_argument(
        '--report', action='store_true', help="Produce coverage, rob and crash reports")
    run_flags.set_defaults(func=run_sim)

    # Fuzz command.
    fuzz_flags = subparsers.add_parser('fuzz', parents=[parent, runtime_common],
                                       help='Fuzz the simulation.')
    fuzz_flags.add_argument(
        '-s', '--simple-ui', action='store_true', help="Disable the graphical TUI.")
    fuzz_flags.add_argument(
        '--aflpath', default="sim-fuzzer", help="Path of fuzzing driver")
    fuzz_flags.add_argument(
        '--indir', default="in", help="Name of the input dir for fuzzing")
    fuzz_flags.add_argument(
        '--outdir', default="out", help="Name of the output dir for fuzzing")
    fuzz_flags.set_defaults(func=run_fuzzer)

    # Uninstrumented BOOM run command.
    uninst_run = subparsers.add_parser('oldrun',
                                       help='Run a program on an uninstrumented BOOM simulation (built with BOOM\'s original Makefile).')
    uninst_run.add_argument(
        'config', help="Name of the configuration to run (e.g. MediumBoomConfig)")
    uninst_run.add_argument(
        'binary', help="RISC-V elf binary to run on the simulation")
    uninst_run.add_argument(
        '--cycles', type=int, default=-1, help="Number of cycles to run the simulation for")
    uninst_run.add_argument(
        '--verbose', action='store_true', help="Enable debug prints")
    uninst_run.add_argument(
        '--logfile', help="Where to log the simulation's output")
    uninst_run.add_argument(
        '--skip-loadmem', action='store_true', help="Load the program through the simulation (slower)")
    uninst_run.add_argument(
        '--loadmem-addr', default="80000000", help="Where to load the program (has not effect if there is --skip_loadmem)")
    uninst_run.add_argument(
        '--dasm', action='store_true', default=False, help="Disassemble output")
    uninst_run.set_defaults(func=run_sim_old)

    # Parse and run.
    args = parser.parse_args()
    validate(args)
    args.func(args)
